### ISSUE TITLE
Aggregates provide null values

### ISSUE THREAD

**Issue by apu-mdo** [graphile/pg-aggregates#12]
I dockerized a PostGraphile app by following steps in https://www.graphile.org/postgraphile/running-postgraphile-in-docker/
Next, I used pg-aggregates to get sum, average, max, min, etc.

Here is the info -

init.sql 
-------

```sql
\connect mypostgraphile;
create schema mygraphile;

/*Create store table in mygraphile schema*/
CREATE TABLE mygraphile.store (
    id SERIAL PRIMARY KEY,
    storename VARCHAR (255) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE mygraphile.store IS
'List of stores.';

/*Create product table in mygraphile schema*/
CREATE TABLE mygraphile.product (
    id SERIAL PRIMARY KEY,
    productname VARCHAR (255) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE mygraphile.product IS
'List of products.';

/*Create brand table in mygraphile schema*/
CREATE TABLE mygraphile.brand (
    id SERIAL PRIMARY KEY,
    brandname VARCHAR (255) NOT NULL,
    price NUMERIC(5,2),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_id INTEGER NOT NULL REFERENCES mygraphile.product(id)
);

COMMENT ON TABLE mygraphile.brand IS
'List of brands.';

/*Create brand table in mygraphile schema*/
CREATE TABLE mygraphile.sale (
    id SERIAL PRIMARY KEY,
    quantity SMALLINT NOT NULL CHECK (quantity > 0),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    store_id INTEGER NOT NULL REFERENCES mygraphile.store(id),
    brand_id INTEGER NOT NULL REFERENCES mygraphile.brand(id)
);

COMMENT ON TABLE mygraphile.sale IS
'Record of sales.';
```

<img width="784" alt="schema" src="https://user-images.githubusercontent.com/81184370/115924406-abff3b80-a44d-11eb-9d51-c30bdf5f66b1.png">

st.sql (dummy data)
--------------------

```sql
\connect mypostgraphile;

/*Create some dummy users*/
INSERT INTO mygraphile.user (username) VALUES
('Benjie'),
('Singingwolfboy'),
('Lexius');

/*Create some dummy posts*/
INSERT INTO mygraphile.post (title, body, author_id) VALUES
('First post example', 'First post body', 1),
('Second post example', 'Second post body', 2),
('Third post example', 'Third post body', 3);

/*Create some dummy stores*/
INSERT INTO mygraphile.store (storename) VALUES
('Store A'),
('Store B'),
('Store C');

/*Create some dummy products*/
INSERT INTO mygraphile.product (productname) VALUES
('Product A'),
('Product B'),
('Product C');

/*Create some dummy brands*/
INSERT INTO mygraphile.brand (brandname, price, product_id) VALUES
('Brand A', 100.50, 1),
('Brand B', 200.50, 2),
('Brand C', 300.50, 1),
('Brand D', 400.50, 2),
('Brand E', 500.50, 3),
('Brand F', 600.00, 3),
('Brand G', 700.50, 1);

/*Create some dummy sales*/
INSERT INTO mygraphile.sale (quantity, store_id, brand_id) VALUES
(5, 1, 1),
(4, 2, 2),
(3, 3, 3),
(2, 2, 4),
(1, 3, 7),
(2, 1, 6),
(3, 2, 5),
(4, 3, 1),
(9, 2, 3),
(7, 1, 4);
```

Dockerfile for GraphQL -
-------------------------

```Dockerfile
FROM node:alpine
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

RUN npm install -g postgraphile
RUN npm install -g @graphile/pg-aggregates

EXPOSE 5000
ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]
```

<img width="877" alt="graphql-Dockerfile" src="https://user-images.githubusercontent.com/81184370/115924591-f1bc0400-a44d-11eb-9762-59c0ea270873.png">

docker-compose.yaml
----------------------

```yaml
version: "3.3"
services:
  db:
    container_name: apu-postgraphile-db
    restart: always
    image: apu-postgraphile-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432
  graphql:
    container_name: apu-postgraphile-graphql
    restart: always
    image: apu-postgraphile-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "mygraphile",
        "--append-plugins",
        "@graphile/pg-aggregates",
      ]

networks:
  network:

volumes:
  db:
```

<img width="879" alt="docker-compose-yaml" src="https://user-images.githubusercontent.com/81184370/115924683-1021ff80-a44e-11eb-95a2-dfce9ab4be59.png">

package.json
--------------

```json
{
  "name": "graphile-apps",
  "version": "0.0.1",
  "description": "api",
  "scripts": {
    "docker-build": "docker-compose build",
    "docker-run": "docker-compose up",
    "start": "npm run docker-build && npm run docker-run"
  },
  "engines": {
    "node": "15.x",
    "npm": "7.x"
  },
  "author": "apu",
  "license": "ISC",
  "dependencies": {
    "@graphile-contrib/pg-simplify-inflector": "^6.1.0",
    "db-migrate": "^0.11.12",
    "db-migrate-pg": "^1.2.2",
    "postgraphile": "^4.12.0-alpha.0",
    "@graphile/pg-aggregates": "^0.1.0"
  }
}
```

<img width="781" alt="package" src="https://user-images.githubusercontent.com/81184370/115924918-6131f380-a44e-11eb-9296-5a8f2e9afe15.png">

Here is the output that I get on graphiql -
------------------------------------------

<img width="1440" alt="Screen Shot 2021-04-23 at 8 45 04 AM" src="https://user-images.githubusercontent.com/81184370/115924979-74dd5a00-a44e-11eb-9131-1c2508b2e083.png">

Please let me know if I missed anything which made me get null values for aggregates.
